server:
  port: 8080


spring:
  application:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        cache:
          interceptor: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  mvc:
    view:
      prefix: '/'
      suffix: '.html'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

default:
  password: saleispower

jwt:
  secret: saleispower




management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

    health:
      show-details=always:

  metrics:
    export:
      prometheus:
        enabled: true

phonepe :
  key : d021e28d-bc19-4fea-b622-41942867d395
  mid : M22LJRRT3FAKQ
  env : PROD

cashfree :
  key : cfsk_ma_test_4101943cd010dd3f59d86a25d03df53a_cce9da94
  mid : TEST10390991bf0adc9155492e36f12619909301
  env : PROD
  callback_uri: https://373d-202-157-76-122.ngrok-free.app
  redirect_uri: http://localhost:3000



# ------------------ public folder path
public_folder :
  absolute : /Users/nareshswami/Documents/springboot/backend/sales-admin/src/main/resources/public
#  absolute : C:\Users\abc\Documents\demo\sales-backend\src\main\resources\public
  get : src/main/resources/public

profile :
  absolute : ${public_folder.absolute}/profiles/
  get : ${public_folder.get}/profiles/

store :
  absolute  : ${public_folder.absolute}/stores/
  get : ${public_folder.get}/stores/

item:
  absolute: ${public_folder.absolute}/items/
  get: ${public_folder.get}/items/

removebg :
  absolute : ${public_folder.absolute}/removebg/
  get : ${public_folder.get}/removebg/

chat :
  absolute : ${public_folder.absolute}/chat/
  get: ${public_folder.get}/chat/

excel:
  export :
    absolute : ${public_folder.absolute}/items_excels/
  update :
    template : ${public_folder.get}/items_excels/update_items/update_item_template.xlsx
  notUpdated:
    absolute: ${public_folder.absolute}/items_excels/not_updated_items/
